### PR TITLE
Creation of the new webpage

### PR DESCRIPTION
**Pull request by Willy-tec**
Initialising all the site

### CODE REVIEW

**Comment by vict0rsch** [comment]
Is this ready to be merged and deployed?

**Comment by vict0rsch** [comment]
Also, I see a bunch of file changes, new pngs etc. can you describe what's new here? What's changing from the current `master`?

**Comment by Willy-tec** [comment]
I refactored all the website, so, there is nothing new from the current master, only a clean site without additional package, or thing from the wordpress context. All the file you can see like png are just old file i reordered to have a cleaner repo.
I guess the site isnt ready for now, i need some adjustement for the mobile responsive design, but you can view the actual website here : https://willy-tec.github.io/codecarbon-static-website/

**Comment by vict0rsch** [comment]
Ok! I'll let you remove WIP and Draft mode when it's ready. Thanks a lot 💪

**Review by benoit-cty — APPROVED** [review]
I will merge you fork in a new branch so you could continue to dev in this repo directly.
And create a new PR from the same repo.

**Pull request merged**
