### PR TITLE
Complete rebuild of the website by William

### PR DESCRIPTION
**Pull request by benoit-cty**
The work in progress can be seen here : https://mlco2.github.io/codecarbon-static-website/

Needed before merging:

- [x] Responsive for mobile
- [ ] Update contributors list
- [x] Update screenshots
- [x] Add Clever Cloud sponsoring support
- [ ] Add a link to [the API](http://api.codecarbon.io/docs) ?

### CODE REVIEW

**Comment by vict0rsch** [comment]
@Willy-tec @benoit-cty do you think we should have a max content width? To 1000 or 1200px? Using full viewport width is too much IMHO on wide screens/high res

**Comment by Willy-tec** [comment]
> @Willy-tec @benoit-cty do you think we should have a max content width? To 1000 or 1200px? Using full viewport width is too much IMHO on wide screens/high res

Yes, i agree, but i already tried the solution, and it's a bit tedious, because of the design.
If i do it the easy way, every section with a background are cropped.
image

But if you think it's an important feature, i can work on it.

**Comment by Willy-tec** [comment]
I will work on it, maybe not now, but soon.
If someone want to access the website on a very large screen, he will have a lot of difficult.

**Comment by vict0rsch** [comment]
Maybe at least the text can have containers with a max-width?

**Comment by benoit-cty** [comment]
Here is what I see in full screen 2 560 x 1 440:
Screenshot 2022-01-13 at 18-31-49 CodeCarbon io

**Comment by Willy-tec** [comment]
I will work on it this weekend.
I will probably fix the max width to 1440, maybe 1280.

**Comment by vict0rsch** [comment]
I think 1280 is the max, there must be a convention somewhere but I think it's as wide as we need it to be :)

**Comment by Willy-tec** [comment]
It's ok for me now.
We can merge it if you like the change.

**Comment by vict0rsch** [comment]
Let's merge! We'll add contributors in another PR

**Pull request merged**
